# Generated by Django 5.2.12 on 2026-03-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SysRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=30, null=True, verbose_name="角色名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=100, null=True, verbose_name="角色权限字符串"),
                ),
                ("create_time", models.DateField(null=True, verbose_name="创建时间")),
                ("update_time", models.DateField(null=True, verbose_name="更新时间")),
                (
                    "remark",
                    models.CharField(max_length=500, null=True, verbose_name="备注"),
                ),
            ],
            options={"db_table": "sys_role",},
        ),
    ]
