# Generated by Django 5.2.12 on 2026-03-13 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0001_initial"),
        ("user", "0003_alter_sysuser_create_time_alter_sysuser_login_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SysUserRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="role.sysrole"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.sysuser"
                    ),
                ),
            ],
            options={"db_table": "sys_user_role",},
        ),
    ]
