# Generated by Django 5.2.12 on 2026-03-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sysuser", old_name="login_data", new_name="login_date",
        ),
        migrations.RenameField(
            model_name="sysuser", old_name="phone_number", new_name="phonenumber",
        ),
    ]
