# Generated by Django 5.2.12 on 2026-03-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_login_data_sysuser_login_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysuser",
            name="create_time",
            field=models.DateField(null=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="login_date",
            field=models.DateField(null=True, verbose_name="最后登录时间"),
        ),
        migrations.AlterField(
            model_name="sysuser",
            name="update_time",
            field=models.DateField(null=True, verbose_name="更新时间"),
        ),
    ]
