# Generated by Django 5.2.12 on 2026-05-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_sysuser_create_time_alter_sysuser_login_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysuser",
            name="status",
            field=models.IntegerField(null=True, verbose_name="账号状态（1正常，0停用）"),
        ),
    ]
